--- 
chrome: 
  image: chinese_chrome
  links: 
    - hub
  ports: 
    - "5902:5900"
  environment: 
    - NODE_MAX_INSTANCES=30
    - NODE_MAX_SESSION=30
    - NODE_REGISTER_CYCLE=5000
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  volumes:
    - /dev/shm:/dev/shm
firefox52: 
  image: "baozhida/selenium-node-firefox:52"
  links: 
    - hub
  ports: 
    - "5903:5900"
  environment: 
    - NODE_MAX_INSTANCES=30
    - NODE_MAX_SESSION=30
    - NODE_REGISTER_CYCLE=5000
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  volumes:
    - /dev/shm:/dev/shm
firefox51: 
  image: "baozhida/selenium-node-firefox:51"
  links: 
    - hub
  ports: 
    - "5901:5900"
  environment: 
    - NODE_MAX_INSTANCES=30
    - NODE_MAX_SESSION=30
    - NODE_REGISTER_CYCLE=5000
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  volumes:
    - /dev/shm:/dev/shm
hub: 
  image: selenium/hub
  ports: 
    - "4444:4444"
